kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "hta-chart.fullname" . }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ template "hta-chart.fullname" . }}-hta
  template:
    metadata:
      labels:
        app: {{ template "hta-chart.fullname" . }}-hta
    spec:
      containers:
        - name: hta
          image: helmtest/app:0.1.0
          env:
            - name: MONGO_URL
              value: mongodb://{{ template "mongodb.fullname" . }}.default.svc.cluster.local:27017
            - name: MONGO_DB
              value: {{ .Values.DbName }}

---

kind: Service
apiVersion: v1
metadata:
  name: {{ template "hta-chart.fullname" . }}-service
spec:
  type: NodePort
  selector: 
    app: {{ template "hta-chart.fullname" . }}-hta
  ports:
    - port: 8080
      targetPort: 3001 